<a href="https://colab.research.google.com/github/rn-byte/Salary_prediction/blob/main/Data_Science_Expo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#So Right Now i have Selected SALARY_PREDICTION dataset For The EXPO. From that dataset we need to find the pattern ,trend and make prediction.

**1. First lets import necessary libraries**

In [2]:
# Imoirting Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print('Libraries Imported')

Libraries Imported

**2. Lets Load and Read the Data Set i.e  [salary_prediction.csv](https://drive.google.com/file/d/1mslWg8xmZYrk5gqFpWaOLtYVxuG_3W5N/view)**

In [6]:
#Loading and Reading CSV File
df=pd.read_csv('/content/salary_prediction.csv')

**Displaying First 10 Data**

In [7]:
#Displaing/ printing First 10 Data
df.head(10)

   YearsExperience  EducationLevel  Age        Salary
0              7.5               4   51  54313.592802
1             19.0               4   49  82663.845282
2             14.6               3   54  72196.732571
3             12.0               1   59  60463.694565
4              3.1               4   35  35756.199258
5              3.1               4   32  37708.558610
6              1.2               2   49  26850.719959
7             17.3               4   38  77493.897641
8             12.0               4   36  64320.462409
9             14.2               2   38  60262.962004